/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MNArifin
 */
public class Home extends javax.swing.JFrame {
    //int Saldo = 100000;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Penarikan = new javax.swing.JButton();
        Transfer = new javax.swing.JButton();
        Penyetoran = new javax.swing.JButton();
        ISaldo = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Bantuan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Penarikan.setText(">");
        Penarikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenarikanActionPerformed(evt);
            }
        });
        getContentPane().add(Penarikan);
        Penarikan.setBounds(380, 260, 50, 40);

        Transfer.setText(">");
        Transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferActionPerformed(evt);
            }
        });
        getContentPane().add(Transfer);
        Transfer.setBounds(380, 200, 50, 40);

        Penyetoran.setText("<");
        Penyetoran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenyetoranActionPerformed(evt);
            }
        });
        getContentPane().add(Penyetoran);
        Penyetoran.setBounds(0, 140, 50, 40);

        ISaldo.setText(">");
        ISaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISaldoActionPerformed(evt);
            }
        });
        getContentPane().add(ISaldo);
        ISaldo.setBounds(380, 140, 50, 40);

        bExit.setText("<");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        getContentPane().add(bExit);
        bExit.setBounds(0, 260, 50, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Informasi Saldo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 140, 124, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Penyetoran");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 140, 90, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Exit");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 260, 80, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Transfer");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 200, 70, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Penarikan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 260, 80, 40);

        Bantuan.setText("<");
        Bantuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BantuanActionPerformed(evt);
            }
        });
        getContentPane().add(Bantuan);
        Bantuan.setBounds(0, 200, 50, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Bantuan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 200, 70, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel7.setText("LAKUKAN TRANSAKSI");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 20, 250, 20);

        setBounds(0, 0, 448, 376);
    }// </editor-fold>//GEN-END:initComponents

    private void PenarikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenarikanActionPerformed
        // TODO add your handling code here:
        //String penarikan = iPenarikan.getText();
        //int jPenarikan = Integer.parseInt(penarikan);
        //int tPenarikan = Saldo-jPenarikan;
        //iSaldo.setText(""+tPenarikan);
        
        new Penarikan().show();
        this.dispose();
    }//GEN-LAST:event_PenarikanActionPerformed

    private void ISaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISaldoActionPerformed
        // TODO add your handling code here:
        //iSaldo.setText(""+Saldo);
        
        new InformasiSaldo().show();
        this.dispose();
        
    }//GEN-LAST:event_ISaldoActionPerformed

    private void TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferActionPerformed
        // TODO add your handling code here:
        //String transfer = iTransfer.getText();
        //String LSaldo = iSaldo.getText();
        //iSaldo.setText(""+LSaldo);
        //int jTransfer = Integer.parseInt(transfer);
        //int lSaldo = Integer.parseInt(LSaldo);
        //int tTransfer = lSaldo-jTransfer;
        //iSaldo.setText(""+tTransfer);
        
        new Transfer().show();
        this.dispose();
    }//GEN-LAST:event_TransferActionPerformed

    private void PenyetoranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenyetoranActionPerformed
        // TODO add your handling code here:
        //String penyetoran = iPenyetoran.getText();
        //String LSaldo = iSaldo.getText();
        //iSaldo.setText(""+LSaldo);
        //int jPenyetoran = Integer.parseInt(penyetoran);
        //int lSaldo = Integer.parseInt(LSaldo);
        //int tPenyetoran = lSaldo+jPenyetoran;
        //iSaldo.setText(""+tPenyetoran);
        
        new Penyetoran().show();
        this.dispose();
    }//GEN-LAST:event_PenyetoranActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bExitActionPerformed

    private void BantuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BantuanActionPerformed
        // TODO add your handling code here:
        new Petunjuk().show();
        this.dispose();
    }//GEN-LAST:event_BantuanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bantuan;
    private javax.swing.JButton ISaldo;
    private javax.swing.JButton Penarikan;
    private javax.swing.JButton Penyetoran;
    private javax.swing.JButton Transfer;
    private javax.swing.JButton bExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
